services:
  - type: web
    name: vitae-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
