"""add ats match columns

Revision ID: 1d89988bca6f
Revises: ed0b08ebec92
Create Date: 2026-05-07 18:44:55.124756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d89988bca6f'
down_revision: Union[str, Sequence[str], None] = 'ed0b08ebec92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_jobs', sa.Column('job_description_text', sa.Text(), nullable=True))
    op.add_column('batch_jobs', sa.Column('job_requirements', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('resume_results', sa.Column('match_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_results', 'match_score')
    op.drop_column('batch_jobs', 'job_requirements')
    op.drop_column('batch_jobs', 'job_description_text')
    # ### end Alembic commands ###
